import { ClineDefaultTool } from "@/shared/tools"

export type PlaceholderToolBundle =
	| "DOC_READ"
	| "CODE_READ"
	| "DOC_WRITE"
	| "LOCAL_EXEC"
	| "PLACEHOLDER_WRITE"
	| "WORKFLOW_ROUTE"
	| "SUBAGENT_COORD"
	| "DIFF_BUILD"
	| "EXTERNAL_RESEARCH"
	| "INDXR_DISCOVERY"
	| "INDXR_SOURCE_READ"
	| "INDXR_SYMBOL_GRAPH"
	| "INDXR_MAINTENANCE"

export const PLACEHOLDER_BUILTIN_BUNDLE_TOOLS = {
	DOC_READ: [
		ClineDefaultTool.LIST_FILES,
		ClineDefaultTool.SEARCH,
		ClineDefaultTool.FILE_READ,
		ClineDefaultTool.FILE_READ_RANGE,
	],
	CODE_READ: [
		ClineDefaultTool.LIST_FILES,
		ClineDefaultTool.SEARCH,
		ClineDefaultTool.LIST_CODE_DEF,
		ClineDefaultTool.FILE_READ,
		ClineDefaultTool.FILE_READ_RANGE,
	],
	DOC_WRITE: [ClineDefaultTool.APPLY_PATCH, ClineDefaultTool.FILE_NEW],
	LOCAL_EXEC: [ClineDefaultTool.BASH],
	PLACEHOLDER_WRITE: [ClineDefaultTool.SET_WORKFLOW_PLACEHOLDERS],
	WORKFLOW_ROUTE: [ClineDefaultTool.USE_SKILL],
	SUBAGENT_COORD: [ClineDefaultTool.USE_SUBAGENTS],
	DIFF_BUILD: [ClineDefaultTool.BUILD_REVIEW_DIFF_OUTPUT],
	EXTERNAL_RESEARCH: [ClineDefaultTool.WEB_SEARCH, ClineDefaultTool.WEB_FETCH],
} as const

export const PLACEHOLDER_INDXR_BUNDLE_TOOLS = {
	INDXR_DISCOVERY: [
		"search_relevant",
		"search_signatures",
		"list_declarations",
		"get_tree",
		"get_imports",
		"get_stats",
		"get_diff_summary",
		"get_token_estimate",
	],
	INDXR_SOURCE_READ: ["get_file_summary", "read_source", "get_file_context", "batch_file_summaries"],
	INDXR_SYMBOL_GRAPH: [
		"lookup_symbol",
		"explain_symbol",
		"get_callers",
		"get_public_api",
		"get_related_tests",
		"get_dependency_graph",
	],
	INDXR_MAINTENANCE: ["regenerate_index"],
} as const

export const ACT_MODE_RESPONSE_TOOL_IDS = [
	ClineDefaultTool.ASK,
	ClineDefaultTool.SEND_USER_MESSAGE,
	ClineDefaultTool.ATTEMPT,
	ClineDefaultTool.ACT_MODE,
] as const

export const PLAN_MODE_RESPONSE_TOOL_IDS = [
	ClineDefaultTool.ASK,
	ClineDefaultTool.SEND_USER_MESSAGE,
	ClineDefaultTool.PLAN_MODE,
] as const

export const ALWAYS_PRESERVED_NATIVE_TOOL_IDS = [
	ClineDefaultTool.NEW_TASK,
	ClineDefaultTool.BROWSER,
	ClineDefaultTool.MCP_ACCESS,
] as const

export const PLACEHOLDER_WORKFLOW_STEP_MATRIX: Record<string, Record<number, readonly PlaceholderToolBundle[]>> = {
	"advanced-elicitation.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: [],
		3: ["DOC_READ", "DOC_WRITE"],
	},
	"brainstorming.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		4: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		5: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
	},
	"check-implementation-readiness.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE"],
		4: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		5: ["DOC_READ", "DOC_WRITE"],
	},
	"cis-design-thinking.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "PLACEHOLDER_WRITE"],
		3: ["PLACEHOLDER_WRITE"],
		4: ["DOC_READ", "PLACEHOLDER_WRITE"],
		5: ["DOC_READ", "PLACEHOLDER_WRITE"],
		6: ["PLACEHOLDER_WRITE"],
		7: ["PLACEHOLDER_WRITE"],
	},
	"cis-innovation-strategy.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "PLACEHOLDER_WRITE"],
		3: ["DOC_READ", "PLACEHOLDER_WRITE"],
		4: ["DOC_READ", "PLACEHOLDER_WRITE"],
		5: ["DOC_READ", "PLACEHOLDER_WRITE"],
		6: ["PLACEHOLDER_WRITE"],
		7: ["PLACEHOLDER_WRITE"],
		8: ["PLACEHOLDER_WRITE"],
		9: ["PLACEHOLDER_WRITE"],
	},
	"cis-problem-solving.md": {
		1: ["DOC_READ"],
		2: [],
		3: ["DOC_READ"],
		4: [],
		5: ["DOC_READ"],
		6: ["DOC_READ"],
		7: [],
		8: [],
		9: [],
	},
	"cis-storytelling.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "PLACEHOLDER_WRITE"],
		3: ["PLACEHOLDER_WRITE"],
		4: ["PLACEHOLDER_WRITE"],
		5: ["PLACEHOLDER_WRITE"],
		6: ["PLACEHOLDER_WRITE"],
		7: ["PLACEHOLDER_WRITE"],
		8: ["PLACEHOLDER_WRITE"],
		9: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
	},
	"code-review.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "LOCAL_EXEC", "DIFF_BUILD", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH"],
		3: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		4: ["DOC_READ", "PLACEHOLDER_WRITE"],
		5: ["SUBAGENT_COORD", "DOC_WRITE"],
		6: ["DOC_READ", "DOC_WRITE", "LOCAL_EXEC"],
		7: [],
	},
	"correct-course.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
	},
	"create-architecture.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "EXTERNAL_RESEARCH"],
		4: ["DOC_READ", "DOC_WRITE"],
		5: ["DOC_READ", "DOC_WRITE"],
		6: ["DOC_READ", "DOC_WRITE"],
		7: ["DOC_READ", "DOC_WRITE"],
		8: ["DOC_READ", "DOC_WRITE"],
	},
	"create-epics-and-stories.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		4: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		5: ["DOC_READ"],
	},
	"create-prd.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_WRITE"],
		4: ["DOC_WRITE"],
		5: ["DOC_WRITE"],
		6: ["DOC_WRITE"],
		7: ["DOC_WRITE"],
		8: ["DOC_WRITE"],
		9: ["DOC_WRITE"],
		10: ["DOC_WRITE"],
		11: ["DOC_WRITE"],
		12: ["DOC_READ", "DOC_WRITE"],
	},
	"create-product-brief.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		3: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		4: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		5: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		6: ["DOC_READ"],
	},
	"create-story.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "LOCAL_EXEC"],
		3: ["DOC_READ"],
		4: ["EXTERNAL_RESEARCH"],
		5: ["DOC_READ", "DOC_WRITE"],
		6: ["DOC_READ", "DOC_WRITE"],
	},
	"create-ux-design.md": {
		1: ["DOC_READ", "DOC_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		3: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		4: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		5: ["DOC_READ", "DOC_WRITE"],
	},
	"dev-story.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "LOCAL_EXEC"],
		3: ["DOC_READ", "DOC_WRITE", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "LOCAL_EXEC"],
		4: ["DOC_READ", "DOC_WRITE", "LOCAL_EXEC"],
	},
	"distillator.md": {
		1: [],
		2: ["DOC_READ", "LOCAL_EXEC"],
		3: ["DOC_READ"],
		4: ["DOC_READ"],
		5: ["DOC_WRITE"],
		6: [],
	},
	"document-project.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "WORKFLOW_ROUTE"],
	},
	"domain-research.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		3: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		4: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		5: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		6: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
	},
	"edit-prd.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ"],
		3: ["DOC_READ"],
		4: ["DOC_READ", "DOC_WRITE"],
		5: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
		6: [],
	},
	"editorial-review-prose.md": {
		1: [],
		2: [],
		3: ["DOC_READ"],
		4: [],
	},
	"editorial-review-structure.md": {
		1: [],
		2: [],
		3: [],
		4: [],
		5: [],
		6: [],
	},
	"generate-project-context.md": {
		1: ["CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_READ", "DOC_WRITE"],
		2: ["DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE"],
	},
	"help.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ"],
		3: ["DOC_READ"],
		4: [],
		5: [],
	},
	"index-docs.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ"],
		3: ["DOC_READ"],
		4: ["DOC_WRITE"],
		5: [],
	},
	"market-research.md": {
		1: ["PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		3: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		4: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		5: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		6: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
	},
	"party-mode.md": {
		1: ["DOC_READ"],
		2: ["SUBAGENT_COORD"],
		3: [],
	},
	"qa-generate-e2e-tests.md": {
		1: ["CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH"],
		2: ["CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_WRITE"],
		3: ["CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "LOCAL_EXEC", "DOC_WRITE"],
	},
	"quick-dev-new-preview.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_WRITE", "LOCAL_EXEC"],
		3: [
			"DOC_READ",
			"CODE_READ",
			"INDXR_DISCOVERY",
			"INDXR_SOURCE_READ",
			"INDXR_SYMBOL_GRAPH",
			"DOC_WRITE",
			"LOCAL_EXEC",
			"SUBAGENT_COORD",
		],
		4: [
			"DOC_READ",
			"CODE_READ",
			"INDXR_DISCOVERY",
			"INDXR_SOURCE_READ",
			"INDXR_SYMBOL_GRAPH",
			"DOC_WRITE",
			"LOCAL_EXEC",
			"SUBAGENT_COORD",
		],
		5: ["DOC_READ", "DOC_WRITE", "LOCAL_EXEC"],
	},
	"quick-dev.md": {
		1: ["DOC_READ", "LOCAL_EXEC"],
		2: ["CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH"],
		3: ["CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_WRITE", "LOCAL_EXEC"],
		4: ["DOC_READ", "DOC_WRITE"],
		5: ["DOC_READ", "LOCAL_EXEC", "SUBAGENT_COORD"],
		6: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_WRITE", "LOCAL_EXEC"],
	},
	"quick-spec.md": {
		1: ["DOC_READ", "DOC_WRITE", "LOCAL_EXEC", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE"],
		4: ["DOC_READ", "DOC_WRITE", "LOCAL_EXEC"],
	},
	"retrospective.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "PLACEHOLDER_WRITE"],
		3: ["DOC_READ"],
		4: [],
		5: ["DOC_WRITE"],
		6: ["WORKFLOW_ROUTE"],
	},
	"review-adversarial-general.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH"],
		3: [],
	},
	"blind-review.md": {
		1: ["DOC_READ", "PLACEHOLDER_WRITE"],
		2: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH", "DOC_WRITE"],
		3: [],
	},
	"review-edge-case-hunter.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH"],
		3: ["DOC_READ", "CODE_READ", "INDXR_DISCOVERY", "INDXR_SOURCE_READ", "INDXR_SYMBOL_GRAPH"],
		4: [],
	},
	"shard-doc.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "LOCAL_EXEC"],
		3: ["LOCAL_EXEC"],
		4: ["DOC_READ"],
		5: [],
		6: ["LOCAL_EXEC"],
	},
	"sprint-planning.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE"],
		4: ["DOC_READ", "DOC_WRITE"],
		5: ["DOC_READ"],
	},
	"sprint-status.md": {
		1: [],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["PLACEHOLDER_WRITE"],
		4: ["WORKFLOW_ROUTE"],
		5: ["DOC_READ"],
		6: ["DOC_READ"],
	},
	"teach-me-testing.md": {
		1: ["DOC_READ"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE"],
		4: ["DOC_READ", "DOC_WRITE"],
		5: ["DOC_READ", "DOC_WRITE"],
	},
	"technical-research.md": {
		1: ["DOC_READ", "DOC_WRITE", "PLACEHOLDER_WRITE"],
		2: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		3: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		4: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		5: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
		6: ["EXTERNAL_RESEARCH", "DOC_READ", "DOC_WRITE"],
	},
	"validate-prd.md": {
		1: ["DOC_READ", "DOC_WRITE"],
		2: ["DOC_READ", "DOC_WRITE"],
		3: ["DOC_READ", "DOC_WRITE"],
		4: ["DOC_READ", "DOC_WRITE"],
		5: ["DOC_READ", "DOC_WRITE"],
		6: ["DOC_READ", "DOC_WRITE"],
		7: ["DOC_READ", "DOC_WRITE"],
		8: ["DOC_READ", "DOC_WRITE"],
		9: ["DOC_READ", "DOC_WRITE"],
		10: ["DOC_READ", "DOC_WRITE"],
		11: ["DOC_READ", "DOC_WRITE"],
		12: ["DOC_READ", "DOC_WRITE", "WORKFLOW_ROUTE"],
	},
}
