export const QUICK_SPEC_DOCUMENT_HEADING_PRODUCT_VISION = "Product Vision"
export const QUICK_SPEC_DOCUMENT_HEADING_USER_CONTEXT = "User Context"
export const QUICK_SPEC_DOCUMENT_HEADING_PROJECT_SCOPE = "Project Scope"
export const QUICK_SPEC_DOCUMENT_HEADING_BOUNDARIES_CONSTRAINTS = "Boundaries & Constraints"
export const QUICK_SPEC_DOCUMENT_HEADING_TECHNICAL_DECISIONS = "Technical Decisions"
export const QUICK_SPEC_DOCUMENT_HEADING_SOLUTION_OVERVIEW = "Solution Overview"
export const QUICK_SPEC_DOCUMENT_HEADING_ACCEPTANCE_CRITERIA = "Acceptance Criteria"
export const QUICK_SPEC_DOCUMENT_HEADING_CODE_MAP = "Code Map"
export const QUICK_SPEC_DOCUMENT_HEADING_SEQUENCING = "Sequencing"
export const QUICK_SPEC_DOCUMENT_HEADING_DEV_AGENT_INSTRUCTIONS = "Dev Agent Instructions"
export const QUICK_SPEC_DOCUMENT_HEADING_IMPLEMENTATION_PHASES = "Implementation Phases"

export const QUICK_SPEC_DOCUMENT_HEADINGS: readonly string[] = [
	QUICK_SPEC_DOCUMENT_HEADING_PRODUCT_VISION,
	QUICK_SPEC_DOCUMENT_HEADING_USER_CONTEXT,
	QUICK_SPEC_DOCUMENT_HEADING_PROJECT_SCOPE,
	QUICK_SPEC_DOCUMENT_HEADING_BOUNDARIES_CONSTRAINTS,
	QUICK_SPEC_DOCUMENT_HEADING_TECHNICAL_DECISIONS,
	QUICK_SPEC_DOCUMENT_HEADING_SOLUTION_OVERVIEW,
	QUICK_SPEC_DOCUMENT_HEADING_ACCEPTANCE_CRITERIA,
	QUICK_SPEC_DOCUMENT_HEADING_CODE_MAP,
	QUICK_SPEC_DOCUMENT_HEADING_SEQUENCING,
	QUICK_SPEC_DOCUMENT_HEADING_DEV_AGENT_INSTRUCTIONS,
	QUICK_SPEC_DOCUMENT_HEADING_IMPLEMENTATION_PHASES,
]

export function buildInitialQuickSpecDocument(): string {
	return `${QUICK_SPEC_DOCUMENT_HEADINGS.map((heading) => `# ${heading}`).join("\n\n")}\n`
}
