export function buildWorkflowStoryFileTemplate(): string {
	return [
		"# Story",
		"",
		"## General Instructions",
		"",
		"- Read this story from top to bottom before making any changes.",
		"- Read each task and subtask in full immediately before executing it.",
		"- Execute only one task or subtask at a time- return to this file and read the next task or subtask before executing. Do not rely on your internal memory when switching to a new task or subtask.",
		"  - Exception: You may execute multiple sequential subtasks with one patch only if they are scoped to the same file, but must review each subtask vs the landed code after the patch to ensure that every subtask was implemented exactly as prescribed before marking the subtask as complete.",
		`  - After completing a task or subtask, update that step's checkbox from "[ ]" to "[x]".`,
		"- Checkbox updates to this story file are allowed in every step in addition to the listed allowed-files set.",
		"- Do not edit any file not listed in the current task or subtask's allowed-files list.",
		"- If you encounter a prescribed change that seems incorrect, stop and inform the user.",
		"- If any ambiguity is discovered, or if any change is needed outside the allowed-files list for the current task or subtask, stop and ask the user before proceeding.",
		"- Implement tasks and subtasks exactly as instructed. If deviation seems necessary, stop, inform the user, and explain why you believe the task or subtask should be carried out differently than prescribed.",
		"- You must avoid these banned development bad habits:",
		`  - "any" typing`,
		"  - val as SomeType",
		"  - as any in tests",
		"  - optional properties most of the time (explicitly model which combinations exist and which don't whenever possible)",
		"  - one-letter generics",
		"  - non-boolean boolean checks",
		"  - bang bang operators (explicitly check for the condition instead)",
		"  - != null (explicitly check for the condition instead)",
		"  - not declaring function return types",
		"  - abuse of type assertions (use them only in special scenarios where the type is clearly known, and give priority to type declarations, interfaces, or generics)",
		"  - Failing to use utility types (use utility types such as partial, pick, omit, etc when appropriate)",
		"  - forcing assertions when types don't match",
		"  - not using enums to manage constants",
		"  - not using generics to abstract duplicated code",
		"  - not using type narrowing",
		"  - not explicitly defining generics parameters",
		"",
		"## Objective",
		"",
		"## Scope",
		"",
		"## Scope Boundary",
		"",
		"## Requirements",
		"",
		"## Known Issues/ Risks/ Technical Debt",
		"",
		"## Tasks",
		"",
		"## Validation",
		"",
	].join("\n")
}
