import { basename } from "node:path"
import type {
	ActiveWorkflowSession,
	WorkflowDecisionBranchTrigger,
	WorkflowDecisionTree,
	WorkflowDefinition,
	WorkflowDeterministicProcedureResult,
	WorkflowPersonaDefinition,
	WorkflowStepDefinition,
	WorkflowStepPromptSource,
	WorkflowValues,
} from "../../types"
import {
	buildQuickDevStep1ToolSchemas,
	buildQuickDevStep2ToolSchemas,
	buildQuickDevStep3ToolSchemas,
} from "./quickDevToolSchemas"

export const QUICK_DEV_WORKFLOW_NAME = "quick-dev"
export const QUICK_DEV_WORKFLOW_DISPLAY_NAME = "quick dev"
export const QUICK_DEV_WORKFLOW_SLASH_COMMAND_NAME = "quick-dev"
export const QUICK_DEV_WORKFLOW_USE_SKILL_NAME = "quick-dev"
export const QUICK_DEV_WORKFLOW_PROJECT_SUBFOLDER = "implementation"
export const QUICK_DEV_WORKFLOW_DESCRIPTION =
	"In this workflow, the agent implements a small project using an implementation spec drafted in the Quick Spec workflow."

export const QUICK_DEV_WORKFLOW_PERSONA: WorkflowPersonaDefinition = {
	name: "Amelia",
	role: "Developer Agent",
	identity: "professional developer with experience in a variety of programming languages",
	communicationStyle: "ultra-succinct, using file paths and acceptance-criteria or task IDs with no fluff",
	capabilities: ["software development"],
	principles: ["implementation must be precise, up to quality standards, and directly aligned with prescribed tasks"],
}

export enum QuickDevWorkflowValueKey {
	ProjectMode = "projectMode",
	ProjectTitle = "projectTitle",
	ProjectFolderName = "projectFolderName",
	SpecFile = "spec_file",
	SpecFileFilename = "spec_file_filename",
}

export const QUICK_DEV_WORKFLOW_VALUE_KEYS: readonly QuickDevWorkflowValueKey[] = [
	QuickDevWorkflowValueKey.ProjectMode,
	QuickDevWorkflowValueKey.ProjectTitle,
	QuickDevWorkflowValueKey.ProjectFolderName,
	QuickDevWorkflowValueKey.SpecFile,
	QuickDevWorkflowValueKey.SpecFileFilename,
]

export const QUICK_DEV_ENTRY_PROJECT_VALUE_KEYS = {
	projectMode: QuickDevWorkflowValueKey.ProjectMode,
	projectTitle: QuickDevWorkflowValueKey.ProjectTitle,
	projectFolderName: QuickDevWorkflowValueKey.ProjectFolderName,
}

export const QUICK_DEV_SPEC_FILE_PREREQUISITE_ID = QuickDevWorkflowValueKey.SpecFile
export const QUICK_DEV_PREREQUISITE_FILES: NonNullable<WorkflowDefinition["prerequisiteFiles"]> = {
	[QUICK_DEV_SPEC_FILE_PREREQUISITE_ID]: {
		id: QUICK_DEV_SPEC_FILE_PREREQUISITE_ID,
		requirement: "required",
		resolutionMode: "interactive",
		producingWorkflowName: "quick-spec",
		projectSubfolderSegments: ["planning"],
		match: { kind: "exact_filename", filename: "quick-spec.md" },
		workflowValueKey: QuickDevWorkflowValueKey.SpecFile,
		outputDocumentReference: "none",
	},
}

const QUICK_DEV_MISSING_SPEC_FILE_ERROR =
	"No implementation specs were found in the selected project folder. You can generate one by running the Quick Spec workflow."
const QUICK_DEV_INVALID_SPEC_FILENAME_ERROR =
	'A file with the required naming conventions was not located. Please ensure that there is a spec file generated by the Quick Spec workflow in the selected project\'s folder with naming convention "quick-spec.md"'
const QUICK_DEV_SPEC_MOVE_FAILED_ERROR =
	"migration of the completed spec to the project's review subfolder failed. Please manually relocate the file."

function createEmptyPromptSource(): WorkflowStepPromptSource {
	return { kind: "none" }
}

function createStepDefinition(args: {
	stepNumber: 1 | 2 | 3
	checklistLabel: string
	decisionTree: WorkflowDecisionTree
	buildPromptSource?: WorkflowStepDefinition["buildPromptSource"]
	promptTemplates?: WorkflowStepDefinition["promptTemplates"]
	buildToolSchema: WorkflowStepDefinition["buildToolSchema"]
}): WorkflowStepDefinition {
	const stepDefinition: WorkflowStepDefinition = {
		id: `step-${args.stepNumber}`,
		stepNumber: args.stepNumber,
		checklistLabel: args.checklistLabel,
		buildPromptSource: args.buildPromptSource ?? createEmptyPromptSource,
		buildToolSchema: args.buildToolSchema,
		decisionTree: args.decisionTree,
	}

	if (args.promptTemplates !== undefined) {
		return { ...stepDefinition, promptTemplates: args.promptTemplates }
	}

	return stepDefinition
}

function readWorkflowStringValue(workflowValues: WorkflowValues, key: QuickDevWorkflowValueKey): string | undefined {
	const value = workflowValues[key]
	if (typeof value !== "string") {
		return undefined
	}

	const trimmedValue = value.trim()
	if (trimmedValue.length === 0) {
		return undefined
	}

	return trimmedValue
}

export function deriveQuickDevSpecFileFilename(session: ActiveWorkflowSession): WorkflowDeterministicProcedureResult {
	const specFile = readWorkflowStringValue(session.workflowValues, QuickDevWorkflowValueKey.SpecFile)
	if (specFile === undefined) {
		return { kind: "failed", errorMessage: QUICK_DEV_MISSING_SPEC_FILE_ERROR }
	}

	const specFileFilename = basename(specFile)
	if (specFileFilename !== "quick-spec.md") {
		return { kind: "failed", errorMessage: QUICK_DEV_INVALID_SPEC_FILENAME_ERROR }
	}

	return {
		kind: "succeeded",
		workflowValueWrites: { [QuickDevWorkflowValueKey.SpecFileFilename]: specFileFilename },
	}
}

const QUICK_DEV_STEP_1_PROMPT_TEMPLATE = `You've been called within a workflow designed to implement one phase within a small project based on documentation built in an upstream workflow. Follow the instructions provided for each step exactly. You will receive additional instructions as you complete steps and unlock additional steps in the workflow.

Read this first: \`{workflow.spec_file}\`
Identify the first incomplete phase in the file, and ask the user to confirm that they'd like you to implement that phase during this workflow. Once they've confirmed, analyze that phase only to build an understanding of the work to be performed. Identify any ambiguities or internal conflicts within the file, and notify the user if any are present.
Once you've read the assigned phase and ensured it is free of internal conflict or ambiguity, send a message to the user informing them that the file is in a good state for execution, and that you will be initiating progression to the execution phase. When the user responds, use workflow_progress_request to progress this workflow to the task execution phase.`

const QUICK_DEV_STEP_2_PROMPT_TEMPLATE = `Implement the phase confirmed by the user in step 1, following the instructions in the document's "Dev Agent Instructions" section exactly. Do not infer missing behavior, do not broaden scope, and do not implement later phases.

 If any task or subtask is ambiguous, internally contradictory, references a missing symbol, requires a change outside the authorized scope for the assigned phase, or cannot be implemented compile-safely as written, stop and report the blocker instead of improvising.

Once all of the assigned phase's tasks and subtasks are complete, stage the files revised, deleted, or generated during implementation. Include the file name and phase number in the commit description.

 After committing your changes, stop and use attempt_completion to provide the user with an implementation summary including:
 - phase completion status
 - any blocker or failed validation, with exact output (if applicable)
 - files changed
 - validation commands and results (if applicable)
 - confirmation that no later-phase work was performed
 - the commit hash from your commit`

function buildStep1PromptSource(): WorkflowStepPromptSource {
	return {
		kind: "current_step_instruction_template",
		currentStepInstructionTemplate: QUICK_DEV_STEP_1_PROMPT_TEMPLATE,
	}
}

function buildStep2PromptSource(): WorkflowStepPromptSource {
	return {
		kind: "current_step_instruction_template",
		currentStepInstructionTemplate: QUICK_DEV_STEP_2_PROMPT_TEMPLATE,
	}
}

function workflowProgressRequestConfirmed(): WorkflowDecisionBranchTrigger {
	return {
		kind: "on_event",
		eventKind: "workflow_progress_request_confirmed",
	}
}

function workflowProgressRequestDenied(): WorkflowDecisionBranchTrigger {
	return {
		kind: "on_event",
		eventKind: "workflow_progress_request_denied",
	}
}

function attemptCompletionSucceeded(): WorkflowDecisionBranchTrigger {
	return {
		kind: "on_event",
		eventKind: "attempt_completion_succeeded",
	}
}

function workflowValuesPersisted(...keys: readonly QuickDevWorkflowValueKey[]): WorkflowDecisionBranchTrigger {
	return {
		kind: "event_predicate",
		matches: ({ triggerEvent }) =>
			triggerEvent.kind === "workflow_values_persisted" && keys.every((key) => triggerEvent.changedKeys.includes(key)),
	}
}

function sourceRouteMatches(sourceRoute: { branchId: string; routeId: string }, branchId: string, routeId: string): boolean {
	return sourceRoute.branchId === branchId && sourceRoute.routeId === routeId
}

function toolBackedOperationSucceeded(branchId: string, routeId: string): WorkflowDecisionBranchTrigger {
	return {
		kind: "event_predicate",
		matches: ({ triggerEvent }) =>
			triggerEvent.kind === "tool_backed_operation_succeeded" &&
			sourceRouteMatches(triggerEvent.sourceRoute, branchId, routeId),
	}
}

function toolBackedOperationFailed(branchId: string, routeId: string): WorkflowDecisionBranchTrigger {
	return {
		kind: "event_predicate",
		matches: ({ triggerEvent }) =>
			triggerEvent.kind === "tool_backed_operation_failed" &&
			sourceRouteMatches(triggerEvent.sourceRoute, branchId, routeId),
	}
}

function buildStep1DecisionTree(): WorkflowDecisionTree {
	return {
		entryBranchId: "step-1-resolve-spec-file",
		branches: {
			"step-1-resolve-spec-file": {
				id: "step-1-resolve-spec-file",
				routes: [
					{
						id: "step-1-resolve-spec-file",
						trigger: { kind: "always" },
						action: {
							kind: "resolve_prerequisite_files",
							prerequisiteIds: [QUICK_DEV_SPEC_FILE_PREREQUISITE_ID],
						},
						followingBranchId: "step-1-derive-spec-file-filename",
					},
				],
			},
			"step-1-derive-spec-file-filename": {
				id: "step-1-derive-spec-file-filename",
				routes: [
					{
						id: "step-1-derive-spec-file-filename",
						trigger: { kind: "always" },
						action: {
							kind: "run_deterministic_procedure",
							instruction: { run: deriveQuickDevSpecFileFilename },
						},
						followingBranchId: "step-1-await-spec-file-filename",
					},
				],
			},
			"step-1-await-spec-file-filename": {
				id: "step-1-await-spec-file-filename",
				routes: [
					{
						id: "step-1-project-prompt",
						trigger: workflowValuesPersisted(QuickDevWorkflowValueKey.SpecFileFilename),
						action: { kind: "project_prompt" },
						followingBranchId: "step-1-await-progress-request",
					},
				],
			},
			"step-1-await-progress-request": {
				id: "step-1-await-progress-request",
				routes: [
					{
						id: "step-1-progress-confirmed",
						trigger: workflowProgressRequestConfirmed(),
						action: {
							kind: "transition_step",
							target: {
								kind: "entry_branch",
								stepNumber: 2,
							},
						},
					},
					{
						id: "step-1-progress-denied",
						trigger: workflowProgressRequestDenied(),
						action: { kind: "project_prompt" },
						followingBranchId: "step-1-await-progress-request",
					},
				],
			},
		},
	}
}

function buildStep2DecisionTree(): WorkflowDecisionTree {
	return {
		entryBranchId: "step-2-project-prompt",
		branches: {
			"step-2-project-prompt": {
				id: "step-2-project-prompt",
				routes: [
					{
						id: "step-2-project-prompt",
						trigger: { kind: "always" },
						action: { kind: "project_prompt" },
						followingBranchId: "step-2-await-attempt-completion",
					},
				],
			},
			"step-2-await-attempt-completion": {
				id: "step-2-await-attempt-completion",
				routes: [
					{
						id: "step-2-transition-to-step-3",
						trigger: attemptCompletionSucceeded(),
						action: {
							kind: "transition_step",
							target: {
								kind: "entry_branch",
								stepNumber: 3,
							},
						},
					},
				],
			},
		},
	}
}

function buildStep3DecisionTree(): WorkflowDecisionTree {
	return {
		entryBranchId: "step-3-move-spec-to-review",
		branches: {
			"step-3-move-spec-to-review": {
				id: "step-3-move-spec-to-review",
				routes: [
					{
						id: "step-3-move-spec-to-review",
						trigger: { kind: "always" },
						action: {
							kind: "move_project_file",
							sourceFolderSegments: ["planning"],
							destinationFolderSegments: ["review"],
							filenameWorkflowValueKey: QuickDevWorkflowValueKey.SpecFileFilename,
						},
						followingBranchId: "step-3-await-spec-move",
					},
				],
			},
			"step-3-await-spec-move": {
				id: "step-3-await-spec-move",
				routes: [
					{
						id: "step-3-complete-after-spec-move",
						trigger: toolBackedOperationSucceeded("step-3-move-spec-to-review", "step-3-move-spec-to-review"),
						action: { kind: "complete_workflow" },
					},
					{
						id: "step-3-terminal-error-after-spec-move-failure",
						trigger: toolBackedOperationFailed("step-3-move-spec-to-review", "step-3-move-spec-to-review"),
						action: {
							kind: "terminal_error",
							errorMessage: QUICK_DEV_SPEC_MOVE_FAILED_ERROR,
						},
					},
				],
			},
		},
	}
}

export const quickDevWorkflowDefinition: WorkflowDefinition = {
	name: QUICK_DEV_WORKFLOW_NAME,
	displayName: QUICK_DEV_WORKFLOW_DISPLAY_NAME,
	description: QUICK_DEV_WORKFLOW_DESCRIPTION,
	slashCommandName: QUICK_DEV_WORKFLOW_SLASH_COMMAND_NAME,
	useSkillName: QUICK_DEV_WORKFLOW_USE_SKILL_NAME,
	persona: QUICK_DEV_WORKFLOW_PERSONA,
	projectSelection: { kind: "interactive" },
	projectOutputPlacement: { kind: "selected_project_subfolder", subfolder: QUICK_DEV_WORKFLOW_PROJECT_SUBFOLDER },
	workflowValueKeys: QUICK_DEV_WORKFLOW_VALUE_KEYS,
	entryProjectValueKeys: QUICK_DEV_ENTRY_PROJECT_VALUE_KEYS,
	entryPanel: { promptMarkdown: QUICK_DEV_WORKFLOW_DESCRIPTION },
	prerequisiteFiles: QUICK_DEV_PREREQUISITE_FILES,
	steps: {
		"step-1": createStepDefinition({
			stepNumber: 1,
			checklistLabel: "Review Assigned Phase",
			decisionTree: buildStep1DecisionTree(),
			buildPromptSource: buildStep1PromptSource,
			promptTemplates: [QUICK_DEV_STEP_1_PROMPT_TEMPLATE],
			buildToolSchema: buildQuickDevStep1ToolSchemas,
		}),
		"step-2": createStepDefinition({
			stepNumber: 2,
			checklistLabel: "Implement Assigned Phase",
			decisionTree: buildStep2DecisionTree(),
			buildPromptSource: buildStep2PromptSource,
			promptTemplates: [QUICK_DEV_STEP_2_PROMPT_TEMPLATE],
			buildToolSchema: buildQuickDevStep2ToolSchemas,
		}),
		"step-3": createStepDefinition({
			stepNumber: 3,
			checklistLabel: "Update Project Records",
			decisionTree: buildStep3DecisionTree(),
			buildToolSchema: buildQuickDevStep3ToolSchemas,
		}),
	},
}
