import { expect } from "chai"
import { describe, it } from "mocha"
import type {
	ActiveWorkflowSession,
	WorkflowBranchTriggerEvent,
	WorkflowDecisionBranchEvaluationInput,
	WorkflowDecisionBranchRoute,
	WorkflowPromptBuilderInput,
	WorkflowStepDefinition,
	WorkflowValues,
} from "../../../types"
import {
	resolveWorkflowBySlashCommand,
	resolveWorkflowByUseSkillName,
	resolveWorkflowDefinition,
} from "../../../WorkflowRegistry"
import { renderWorkflowPromptTemplate } from "../../../workflowPromptTemplates"
import {
	deriveQuickDevSpecFileFilename,
	QUICK_DEV_ENTRY_PROJECT_VALUE_KEYS,
	QUICK_DEV_PREREQUISITE_FILES,
	QUICK_DEV_SPEC_FILE_PREREQUISITE_ID,
	QUICK_DEV_WORKFLOW_DESCRIPTION,
	QUICK_DEV_WORKFLOW_PERSONA,
	QUICK_DEV_WORKFLOW_VALUE_KEYS,
	QuickDevWorkflowValueKey,
	quickDevWorkflowDefinition,
} from ".."
import {
	buildQuickDevStep1ToolSchemas,
	buildQuickDevStep2ToolSchemas,
	buildQuickDevStep3ToolSchemas,
} from "../quickDevToolSchemas"

const TEST_SPEC_FILE = "/tmp/quick-dev-project/planning/quick-spec.md"
const TEST_SPEC_FILE_FILENAME = "quick-spec.md"
const MISSING_SPEC_FILE_ERROR =
	"No implementation specs were found in the selected project folder. You can generate one by running the Quick Spec workflow."
const INVALID_SPEC_FILENAME_ERROR =
	'A file with the required naming conventions was not located. Please ensure that there is a spec file generated by the Quick Spec workflow in the selected project\'s folder with naming convention "quick-spec.md"'
const SPEC_MOVE_FAILED_ERROR =
	"migration of the completed spec to the project's review subfolder failed. Please manually relocate the file."

function createSession(args: {
	activeStepNumber: number
	activeBranchId: string
	workflowValues: WorkflowValues
}): ActiveWorkflowSession {
	return {
		activeStepNumber: args.activeStepNumber,
		workflowValues: args.workflowValues,
		projectSelection: {
			projectMode: "existing",
			projectTitle: "Quick Dev Project",
			projectFolderName: "quick-dev-project",
		},
		lifecycle: {
			projectSelectionCompleted: true,
		},
		entryArtifactResolution: undefined,
		prerequisiteFileResolutions: [],
		ui: {
			formSession: undefined,
			stepResolutionSession: undefined,
			suppressedWorkflowFormIds: [],
			suppressedWorkflowStepResolutionRoutes: [],
		},
		branchContext: {
			activeBranchId: args.activeBranchId,
		},
	}
}

function createPredicateInput(args: {
	activeBranchId: string
	workflowValues: WorkflowValues
	step: WorkflowStepDefinition
	triggerEvent: WorkflowBranchTriggerEvent
}): WorkflowDecisionBranchEvaluationInput & { triggerEvent: WorkflowBranchTriggerEvent } {
	return {
		activeBranchId: args.activeBranchId,
		workflowValues: args.workflowValues,
		step: args.step,
		session: createSession({
			activeStepNumber: args.step.stepNumber,
			activeBranchId: args.activeBranchId,
			workflowValues: args.workflowValues,
		}),
		triggerEvent: args.triggerEvent,
	}
}

function getStep(stepId: WorkflowStepDefinition["id"]): WorkflowStepDefinition {
	const step = quickDevWorkflowDefinition.steps[stepId]
	if (step === undefined) {
		throw new Error(`Missing quick-dev step ${stepId}.`)
	}

	return step
}

function findStepRoute(stepId: WorkflowStepDefinition["id"], branchId: string, routeId: string): WorkflowDecisionBranchRoute {
	const step = getStep(stepId)
	const branch = step.decisionTree.branches[branchId]
	if (branch === undefined) {
		throw new Error(`Missing quick-dev branch ${branchId}.`)
	}

	const route = branch.routes.find((candidate) => candidate.id === routeId)
	if (route === undefined) {
		throw new Error(`Missing quick-dev route ${branchId}/${routeId}.`)
	}

	return route
}

function createPromptInput(args: {
	stepId: WorkflowStepDefinition["id"]
	activeBranchId: string
	workflowValues: WorkflowValues
}): WorkflowPromptBuilderInput {
	const step = getStep(args.stepId)
	return {
		session: createSession({
			activeStepNumber: step.stepNumber,
			activeBranchId: args.activeBranchId,
			workflowValues: args.workflowValues,
		}),
		step,
	}
}

function getPromptInstructions(args: {
	stepId: WorkflowStepDefinition["id"]
	activeBranchId: string
	workflowValues: WorkflowValues
}): string {
	const promptSource = getStep(args.stepId).buildPromptSource(createPromptInput(args))
	if (promptSource.kind !== "current_step_instruction_template") {
		throw new Error(`Expected quick-dev ${args.stepId} to provide current step instructions.`)
	}

	return renderWorkflowPromptTemplate({
		template: promptSource.currentStepInstructionTemplate,
		workflowValueKeys: quickDevWorkflowDefinition.workflowValueKeys,
		workflowValues: args.workflowValues,
		context: `quick-dev ${args.stepId} test prompt`,
	})
}

function buildWorkflowValuesPersistedEvent(changedKeys: readonly string[]): WorkflowBranchTriggerEvent {
	return {
		kind: "workflow_values_persisted",
		changedKeys,
	}
}

function buildToolBackedOperationSucceededEvent(branchId: string, routeId: string): WorkflowBranchTriggerEvent {
	return {
		kind: "tool_backed_operation_succeeded",
		sourceRoute: { branchId, routeId },
	}
}

function buildToolBackedOperationFailedEvent(branchId: string, routeId: string): WorkflowBranchTriggerEvent {
	return {
		kind: "tool_backed_operation_failed",
		sourceRoute: { branchId, routeId },
		errorMessage: "move failed",
	}
}

function expectEventPredicateMatches(args: {
	stepId: WorkflowStepDefinition["id"]
	branchId: string
	route: WorkflowDecisionBranchRoute
	workflowValues: WorkflowValues
	triggerEvent: WorkflowBranchTriggerEvent
}): void {
	if (args.route.trigger.kind !== "event_predicate") {
		throw new Error(`Expected event_predicate trigger, received ${args.route.trigger.kind}.`)
	}

	expect(
		args.route.trigger.matches(
			createPredicateInput({
				activeBranchId: args.branchId,
				workflowValues: args.workflowValues,
				step: getStep(args.stepId),
				triggerEvent: args.triggerEvent,
			}),
		),
	).to.equal(true)
}

describe("quickDevWorkflow", () => {
	it("defines the Quick Dev workflow identity, persona, values, prerequisite, and steps", () => {
		expect(quickDevWorkflowDefinition.name).to.equal("quick-dev")
		expect(quickDevWorkflowDefinition.displayName).to.equal("quick dev")
		expect(quickDevWorkflowDefinition.description).to.equal(QUICK_DEV_WORKFLOW_DESCRIPTION)
		expect(quickDevWorkflowDefinition.slashCommandName).to.equal("quick-dev")
		expect(quickDevWorkflowDefinition.useSkillName).to.equal("quick-dev")
		expect(quickDevWorkflowDefinition.projectSelection).to.deep.equal({ kind: "interactive" })
		expect(quickDevWorkflowDefinition.projectOutputPlacement).to.deep.equal({
			kind: "selected_project_subfolder",
			subfolder: "implementation",
		})
		expect(Object.hasOwn(quickDevWorkflowDefinition, "projectSubfolder")).to.equal(false)
		expect(quickDevWorkflowDefinition.persona).to.deep.equal(QUICK_DEV_WORKFLOW_PERSONA)
		expect(quickDevWorkflowDefinition.entryPanel.promptMarkdown).to.equal(QUICK_DEV_WORKFLOW_DESCRIPTION)
		expect(quickDevWorkflowDefinition.workflowValueKeys).to.deep.equal(QUICK_DEV_WORKFLOW_VALUE_KEYS)
		expect(quickDevWorkflowDefinition.entryProjectValueKeys).to.deep.equal(QUICK_DEV_ENTRY_PROJECT_VALUE_KEYS)
		expect(quickDevWorkflowDefinition.workflowForms).to.equal(undefined)
		expect(quickDevWorkflowDefinition.artifacts).to.equal(undefined)
		expect(Object.keys(quickDevWorkflowDefinition.steps)).to.deep.equal(["step-1", "step-2", "step-3"])
		expect(Object.values(quickDevWorkflowDefinition.steps).map((step) => step.stepNumber)).to.deep.equal([1, 2, 3])
		expect(Object.values(quickDevWorkflowDefinition.steps).map((step) => step.checklistLabel)).to.deep.equal([
			"Review Assigned Phase",
			"Implement Assigned Phase",
			"Update Project Records",
		])
		expect(quickDevWorkflowDefinition.prerequisiteFiles).to.deep.equal(QUICK_DEV_PREREQUISITE_FILES)
	})

	it("resolves from the registry by canonical quick-dev names and rejects .md aliases", () => {
		expect(resolveWorkflowDefinition("quick-dev")).to.equal(quickDevWorkflowDefinition)
		expect(resolveWorkflowBySlashCommand("quick-dev")).to.equal(quickDevWorkflowDefinition)
		expect(resolveWorkflowByUseSkillName("quick-dev")).to.equal(quickDevWorkflowDefinition)
		expect(resolveWorkflowDefinition("quick-dev.md")).to.equal(undefined)
		expect(resolveWorkflowBySlashCommand("quick-dev.md")).to.equal(undefined)
		expect(resolveWorkflowByUseSkillName("quick-dev.md")).to.equal(undefined)
	})

	it("declares the required quick-spec prerequisite exactly", () => {
		const prerequisite = QUICK_DEV_PREREQUISITE_FILES[QUICK_DEV_SPEC_FILE_PREREQUISITE_ID]

		expect(prerequisite).to.deep.equal({
			id: "spec_file",
			requirement: "required",
			resolutionMode: "interactive",
			producingWorkflowName: "quick-spec",
			projectSubfolderSegments: ["planning"],
			match: { kind: "exact_filename", filename: "quick-spec.md" },
			workflowValueKey: "spec_file",
			outputDocumentReference: "none",
		})
	})

	it("derives and validates the quick-spec filename from the selected prerequisite path", () => {
		expect(
			deriveQuickDevSpecFileFilename(
				createSession({
					activeStepNumber: 1,
					activeBranchId: "step-1-derive-spec-file-filename",
					workflowValues: { spec_file: TEST_SPEC_FILE },
				}),
			),
		).to.deep.equal({
			kind: "succeeded",
			workflowValueWrites: { [QuickDevWorkflowValueKey.SpecFileFilename]: TEST_SPEC_FILE_FILENAME },
		})
		expect(
			deriveQuickDevSpecFileFilename(
				createSession({
					activeStepNumber: 1,
					activeBranchId: "step-1-derive-spec-file-filename",
					workflowValues: {},
				}),
			),
		).to.deep.equal({ kind: "failed", errorMessage: MISSING_SPEC_FILE_ERROR })
		expect(
			deriveQuickDevSpecFileFilename(
				createSession({
					activeStepNumber: 1,
					activeBranchId: "step-1-derive-spec-file-filename",
					workflowValues: { spec_file: "/tmp/quick-dev-project/planning/not-quick-spec.md" },
				}),
			),
		).to.deep.equal({ kind: "failed", errorMessage: INVALID_SPEC_FILENAME_ERROR })
	})

	it("routes Step 1 through prerequisite resolution, filename derivation, project prompt, and progress gating", () => {
		const workflowValues = { spec_file: TEST_SPEC_FILE, spec_file_filename: TEST_SPEC_FILE_FILENAME }
		const resolveRoute = findStepRoute("step-1", "step-1-resolve-spec-file", "step-1-resolve-spec-file")
		const deriveRoute = findStepRoute("step-1", "step-1-derive-spec-file-filename", "step-1-derive-spec-file-filename")
		const promptRoute = findStepRoute("step-1", "step-1-await-spec-file-filename", "step-1-project-prompt")
		const confirmedRoute = findStepRoute("step-1", "step-1-await-progress-request", "step-1-progress-confirmed")
		const deniedRoute = findStepRoute("step-1", "step-1-await-progress-request", "step-1-progress-denied")

		expect(resolveRoute.action).to.deep.equal({
			kind: "resolve_prerequisite_files",
			prerequisiteIds: ["spec_file"],
		})
		expect(resolveRoute.followingBranchId).to.equal("step-1-derive-spec-file-filename")
		expect(deriveRoute.action.kind).to.equal("run_deterministic_procedure")
		expect(deriveRoute.followingBranchId).to.equal("step-1-await-spec-file-filename")
		if (deriveRoute.action.kind !== "run_deterministic_procedure") {
			throw new Error(`Expected run_deterministic_procedure, received ${deriveRoute.action.kind}.`)
		}
		expect(deriveRoute.action.instruction.run).to.equal(deriveQuickDevSpecFileFilename)
		expectEventPredicateMatches({
			stepId: "step-1",
			branchId: "step-1-await-spec-file-filename",
			route: promptRoute,
			workflowValues,
			triggerEvent: buildWorkflowValuesPersistedEvent(["spec_file_filename"]),
		})
		expect(promptRoute.action).to.deep.equal({ kind: "project_prompt" })
		expect(promptRoute.followingBranchId).to.equal("step-1-await-progress-request")
		expect(confirmedRoute.trigger).to.deep.equal({
			kind: "on_event",
			eventKind: "workflow_progress_request_confirmed",
		})
		expect(confirmedRoute.action).to.deep.equal({
			kind: "transition_step",
			target: { kind: "entry_branch", stepNumber: 2 },
		})
		expect(deniedRoute.trigger).to.deep.equal({
			kind: "on_event",
			eventKind: "workflow_progress_request_denied",
		})
		expect(deniedRoute.action).to.deep.equal({ kind: "project_prompt" })
		expect(deniedRoute.followingBranchId).to.equal("step-1-await-progress-request")
	})

	it("routes Step 2 attempt completion to Step 3", () => {
		const projectPromptRoute = findStepRoute("step-2", "step-2-project-prompt", "step-2-project-prompt")
		const completionRoute = findStepRoute("step-2", "step-2-await-attempt-completion", "step-2-transition-to-step-3")

		expect(projectPromptRoute.action).to.deep.equal({ kind: "project_prompt" })
		expect(projectPromptRoute.followingBranchId).to.equal("step-2-await-attempt-completion")
		expect(completionRoute.trigger).to.deep.equal({ kind: "on_event", eventKind: "attempt_completion_succeeded" })
		expect(completionRoute.action).to.deep.equal({
			kind: "transition_step",
			target: { kind: "entry_branch", stepNumber: 3 },
		})
	})

	it("routes Step 3 through quick-spec relocation and completion or terminal error", () => {
		const workflowValues = { spec_file: TEST_SPEC_FILE, spec_file_filename: TEST_SPEC_FILE_FILENAME }
		const moveRoute = findStepRoute("step-3", "step-3-move-spec-to-review", "step-3-move-spec-to-review")
		const successRoute = findStepRoute("step-3", "step-3-await-spec-move", "step-3-complete-after-spec-move")
		const failureRoute = findStepRoute("step-3", "step-3-await-spec-move", "step-3-terminal-error-after-spec-move-failure")

		expect(moveRoute.action).to.deep.equal({
			kind: "move_project_file",
			sourceFolderSegments: ["planning"],
			destinationFolderSegments: ["review"],
			filenameWorkflowValueKey: "spec_file_filename",
		})
		expect(moveRoute.followingBranchId).to.equal("step-3-await-spec-move")
		expectEventPredicateMatches({
			stepId: "step-3",
			branchId: "step-3-await-spec-move",
			route: successRoute,
			workflowValues,
			triggerEvent: buildToolBackedOperationSucceededEvent("step-3-move-spec-to-review", "step-3-move-spec-to-review"),
		})
		expect(successRoute.action).to.deep.equal({ kind: "complete_workflow" })
		expectEventPredicateMatches({
			stepId: "step-3",
			branchId: "step-3-await-spec-move",
			route: failureRoute,
			workflowValues,
			triggerEvent: buildToolBackedOperationFailedEvent("step-3-move-spec-to-review", "step-3-move-spec-to-review"),
		})
		expect(failureRoute.action).to.deep.equal({
			kind: "terminal_error",
			errorMessage: SPEC_MOVE_FAILED_ERROR,
		})
	})

	it("builds Step 1 and Step 2 prompt sources with materialized workflow values and keeps Step 3 promptless", () => {
		const workflowValues = { spec_file: TEST_SPEC_FILE, spec_file_filename: TEST_SPEC_FILE_FILENAME }
		const step1Instructions = getPromptInstructions({
			stepId: "step-1",
			activeBranchId: "step-1-resolve-spec-file",
			workflowValues,
		})
		const step2Instructions = getPromptInstructions({
			stepId: "step-2",
			activeBranchId: "step-2-project-prompt",
			workflowValues,
		})

		expect(step1Instructions).to.include(TEST_SPEC_FILE)
		expect(step1Instructions).to.include(`Read this first: \`${TEST_SPEC_FILE}\``)
		expect(step1Instructions).to.include("workflow_progress_request")
		expect(step1Instructions).to.include("Identify the first incomplete phase")
		expect(step1Instructions).not.to.include("{workflow.spec_file}")
		expect(step1Instructions).not.to.include("### Prompt")
		expect(step1Instructions).not.to.include("### Progression Rule")
		expect(step1Instructions).not.to.include("# Tool Schema Override")
		expect(step1Instructions).not.to.include("# Focus Chain Tasks")
		expect(step2Instructions).to.include("Implement the phase confirmed by the user in step 1")
		expect(step2Instructions).to.include("attempt_completion")
		expect(step2Instructions).to.include("phase completion status")
		expect(step2Instructions).to.include("the commit hash from your commit")
		expect(step2Instructions).not.to.include("workflow must progress to step 3")
		expect(step2Instructions).not.to.include("### Prompt")
		expect(step2Instructions).not.to.include("### Progression Rule")
		expect(step2Instructions).not.to.include("# Tool Schema Override")
		expect(step2Instructions).not.to.include("# Focus Chain Tasks")

		const step3PromptSource = getStep("step-3").buildPromptSource(
			createPromptInput({
				stepId: "step-3",
				activeBranchId: "step-3-move-spec-to-review",
				workflowValues: { spec_file: TEST_SPEC_FILE, spec_file_filename: TEST_SPEC_FILE_FILENAME },
			}),
		)
		expect(step3PromptSource).to.deep.equal({ kind: "none" })
		expect(getStep("step-3").promptTemplates).to.equal(undefined)
	})

	it("delegates every step to module-owned tool schema builders", () => {
		const workflowValues = { spec_file: TEST_SPEC_FILE, spec_file_filename: TEST_SPEC_FILE_FILENAME }
		const step1PromptInput = createPromptInput({
			stepId: "step-1",
			activeBranchId: "step-1-resolve-spec-file",
			workflowValues,
		})
		const step2PromptInput = createPromptInput({
			stepId: "step-2",
			activeBranchId: "step-2-project-prompt",
			workflowValues,
		})
		const step3PromptInput = createPromptInput({
			stepId: "step-3",
			activeBranchId: "step-3-move-spec-to-review",
			workflowValues,
		})

		expect(quickDevWorkflowDefinition.steps["step-1"].buildToolSchema(step1PromptInput)).to.deep.equal(
			buildQuickDevStep1ToolSchemas(),
		)
		expect(quickDevWorkflowDefinition.steps["step-2"].buildToolSchema(step2PromptInput)).to.deep.equal(
			buildQuickDevStep2ToolSchemas(),
		)
		expect(quickDevWorkflowDefinition.steps["step-3"].buildToolSchema(step3PromptInput)).to.deep.equal(
			buildQuickDevStep3ToolSchemas(),
		)
	})

	it("does not reference legacy source files, authoring markers, or unauthorized runtime artifacts", () => {
		const serializedDefinition = JSON.stringify(quickDevWorkflowDefinition)
		if (serializedDefinition === undefined) {
			throw new Error("Expected quick-dev workflow definition to serialize.")
		}

		expect(serializedDefinition).not.to.include("/Users/robertboston/Documents/Cline/Workflows/quick-dev.md")
		expect(serializedDefinition).not.to.include(".cline/workflow-config.yaml")
		expect(serializedDefinition).not.to.include("bmad")
		expect(serializedDefinition).not.to.include("BMAD")
		expect(serializedDefinition).not.to.include("quick-dev.md")
		expect(serializedDefinition).not.to.include("build_workflow_document")
		expect(serializedDefinition).not.to.include("create_workflow_artifact")
		expect(serializedDefinition).not.to.include("archive_workflow_artifact")
		expect(serializedDefinition).not.to.include("delete_workflow_artifact")
		expect(serializedDefinition).not.to.include("move_workflow_project_file")
		expect(serializedDefinition).not.to.include("set_workflow_values")
		expect(serializedDefinition).not.to.include("ask_followup_question")
		expect(serializedDefinition).not.to.include("use_subagents")
		expect(serializedDefinition).not.to.include("use_skill")
	})
})
